### PR TITLE
Removing prompts from Windows script

### LINKED ISSUE #22: Windows script prompts for input
**Describe the bug**
The [instructions] for using this script clearly state "no command prompts are given during the installation process." When I invoke commands 1+2 (at link) through WinRM, however, it is clear that the script [stops for a prompt](https://github.com/GoogleCloudPlatform/compute-gpu-installation/blob/main/windows/install_gpu_driver.ps1#L57) with the message:

> Press any key to continue

[instructions]: https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#windows

What am I missing? I believe that I'm running as Administrator, but is this prompt ignored under some conditions?

**Environment**
 - Operating system: What OS are you running, would be best to point at specific disk image on GCP you are using if it's public.

windows-2016 image family (latest)

 - Graphics card: What kind of GPU are you trying to use. How many devices do you have attached?

n1-standard-8 with 1 Tesla T4 attached

**To Reproduce**
Steps to reproduce the behavior. A copy-paste of the commands you executed and the output you got. The Linux installation script by default saves its' output to `/opt/google/gpu-installer/` - please provide the files you find there.

I am supplying the script below to a [Powershell provisioner](https://developer.hashicorp.com/packer/docs/provisioners/powershell) (WinRM) in packer. It is configured with `elevated_user = "Administrator"`.

```ps1
Set-StrictMode -Version latest
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = 'Tls12'
Invoke-WebRequest https://github.com/GoogleCloudPlatform/compute-gpu-installation/raw/main/windows/install_gpu_driver.ps1 -OutFile C:\install_gpu_driver.ps1
C:\install_gpu_driver.ps1
```

I'll admit to inexperience with Windows PowerShell scripting, but the script seems plainly designed to prompt for input.

### PR DESCRIPTION
**Pull request by m-strzelczyk**
Fixes #22 

The script should not wait for user input. It's meant to be used hands-off in automation.

Script will no longer wait for user to press any key and just install the driver if it's not there. Even if there's no GPU installed.

### CODE REVIEW

**Comment by tpdownes** [comment]
I have tested this using the following script:

```ps1
Set-StrictMode -Version latest
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = 'Tls12'

Invoke-WebRequest https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/371284fcad3317a15c3a043302188fd85c9928dd/windows/install_gpu_driver.ps1 -OutFile C:\install_gpu_driver.ps1
& C:\install_gpu_driver.ps1
```

I had to use `&` vs `Start-Process` because `&` will respect the SecurityProtocol setting and `Start-Process` does not. Maybe there is some smarter way.

It takes a long time to run (1.5GB out of 3.0GB downloaded) so I have not yet seen it complete (and it's end of workday), but I wanted to report initial success.

**Comment by tpdownes** [comment]
After installation completed, I could not find nvidia-smi.exe under C:\Program Files or C:\Windows\System32. I think the explanation is that CUDA Toolkit 12.1.1 doesn't appear to support Windows 2016 (entirely reasonable). 11.8 does:

https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=Server2016&target_type=exe_local

I will manually install that and see if nvidia-smi.exe works.

But, it may be necessary to modify this script to handle 2016 as a special case (like K80). I will investigate how important Windows 2016 is to the customer in question (it may be something they want to move on from) and report back.

**Comment by tpdownes** [comment]
I made a mistake in testing and forgot to attach a GPU to one of the VMs. So that might be part of it, but here are the problems I see:

1. nvidia-smi.exe is now installed to C:\Windows\System32 so re-running the script attempts installation of the drivers again
2. Windows 2016 doesn't appear to be supported by the 12.1 installer.

Before merging this PR, I think you'll want to change the path it uses to detect nvidia-smi.exe. Then I would create a task to address (2) by using the alternative EXE shown below.

```ps1
Set-StrictMode -Version latest
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = 'Tls12'

# WINDOWS 2019 and above
# Invoke-WebRequest https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/371284fcad3317a15c3a043302188fd85c9928dd/windows/install_gpu_driver.ps1 -OutFile C:\install_gpu_driver.ps1
# & C:\install_gpu_driver.ps1

# OR FOR WINDOWS 2016!
Invoke-WebRequest https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_522.06_windows.exe -OutFile C:\cuda_11.8.0_522.06_windows.exe
Start-Process -FilePath C:\cuda_11.8.0_522.06_windows.exe -ArgumentList '/s /n' -Wait
```

**Comment by m-strzelczyk** [comment]
I have updated the Script to download an older version of the driver and to check for `nvidia-smi.exe` in a more universal way. I'll still need to check this with other versions of Windows before merging, but it should be fine for Windows 2016.

**Comment by tpdownes** [comment]
I tested this script:

- manually running it inside a Windows 2016 datacenter image (w/Desktop)
- by downloading it and providing it directly to Packer as a [PowerShell provisioner](https://developer.hashicorp.com/packer/docs/provisioners/powershell)

In both cases, it installed the NVIDIA driver. When I try running it a second time, it shows me the stdout of the nvidia-smi.exe command. That's not a huge deal - maybe it's a good thing so that you know what driver is already there.

I'm not sure `C:\Program Files\...` is in the "PATH" of Windows commands so I'm not sure how portable the solution is. But I defer to your expertise on that.

LGTM .

**Pull request merged**
